site_name: FactryFlow
# site_description: FastAPI framework, high performance, easy to learn, fast to code, ready for production
  
theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  icon:
    repo: fontawesome/brands/github-alt
  language: en

repo_url: https://github.com/Yacobolo/factryflow
repo_name: factryflow

nav:
  - Welcome: index.md
  # - Getting Started:
  #   - Installation: getting-started/installation.md
  #   - Quickstart: getting-started/quickstart.md
  #   - Tutorial: getting-started/tutorial.md
  # - User Guide:
  - Technical Documentation:
    - Architecture: technical-documentation/architecture.md
    - ER Diagram: technical-documentation/er-diagram.md
    - Database Schema: technical-documentation/database-schema.md
    - Database Naming Conventions: technical-documentation/database-naming-conventions.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
